services:
  har-torch:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: hoge-torch
    privileged: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 2
            capabilities: [gpu]
    volumes: # Mount Local:Container
      - /home/hoge/code/:/mnt/code
      - /home/hoge/.ssh/:/mnt/.ssh/
    ports:
      - "5450:8888"
    shm_size: 8gb